name: Lee Munroe
markdown: redcarpet
pygments: true
baseurl: /blog
permalink: /:title
paginate: 10
paginate_path: /blog/page/:num
description: Blog of Product and UX Designer Lee Munroe
url: http://www.leemunroe.com